# Generated by Django 5.2.15 on 2026-06-07 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-is_default', 'id'], 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='sellerprofile',
            options={'ordering': ['-is_best_seller', '-rating', '-created_at']},
        ),
    ]
