# Generated by Django 5.2.15 on 2026-06-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='courier_ref',
            field=models.CharField(blank=True, help_text='Courier-side order id (for cancel)', max_length=60),
        ),
    ]
