# Generated by Django 5.2.15 on 2026-06-07 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='oem/makes/')),
                ('country', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OemPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oem_number', models.CharField(db_index=True, max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='oem/parts/')),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('source', models.CharField(default='oriparts', max_length=40)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oem_parts', to='catalog.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_from', models.PositiveIntegerField(blank=True, null=True)),
                ('year_to', models.PositiveIntegerField(blank=True, null=True)),
                ('oem_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oem.oempart')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('year_start', models.PositiveIntegerField(default=2000)),
                ('year_end', models.PositiveIntegerField(blank=True, null=True)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='oem.vehiclemake')),
            ],
            options={
                'ordering': ['make__name', 'name'],
                'unique_together': {('make', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RegistrationLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(db_index=True, max_length=12)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=20)),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oem.vehiclemodel')),
            ],
        ),
        migrations.AddField(
            model_name='oempart',
            name='compatible_models',
            field=models.ManyToManyField(related_name='oem_parts', through='oem.Fitment', to='oem.vehiclemodel'),
        ),
        migrations.AddField(
            model_name='fitment',
            name='vehicle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oem.vehiclemodel'),
        ),
        migrations.AlterUniqueTogether(
            name='fitment',
            unique_together={('oem_part', 'vehicle_model')},
        ),
    ]
